name: arb_resource_value_parser
description: A parser for ARB resource value, with support for ICU messageformat.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.4 <3.0.0'


dependencies:
  petitparser: ^4.4.0
  built_collection: ^5.1.1
  built_value: ^8.1.3
  trotter: ^2.0.0-dev.1
  collection: ^1.15.0

dev_dependencies:
  test: ^1.19.2
  build_runner: ^2.1.4
  built_value_generator: ^8.1.3
  lints: ^1.0.0
