name: arb_file_parser
description: A parser for the ApplicationResourceBundle (ARB) file format
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.4 <3.0.0'


dependencies:
  arb_resource_value_parser:
    path: ../arb_resource_value_parser
  built_collection: ^5.1.1
  built_value: ^8.1.3
  collection: ^1.15.0

dev_dependencies:
  build_runner: ^2.1.4
  built_value_generator: ^8.1.3
  lints: ^1.0.0
  test: ^1.16.0
